[package]
name = "frt"
version = "0.1.0"
edition = "2021"

description = "2nd Gen FGI Rendering Tool"
readme = "README.md"
homepage = "https://about.furrygames.top/frt"
repository = "https://github.com/FurryGamesIndex/frt-rs.git"
license = "AGPL-3.0-or-later"
authors = ["UtopicPanther <upanther@furrygames.top>"]

[lib]
name = "libfrt"
path = "src/libfrt/lib.rs"

[[bin]]
name = "frt"
path = "src/frt/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
toml = "0.5"
clap = { version = "4.0", features = ["derive"] }
anyhow = { version = "1.0", features = ["backtrace"] }
regex = "1"