[package]
name = "frt"
version = "0.1.0"
edition = "2021"

[lib]
name = "libfrt"
path = "src/libfrt/lib.rs"

[[bin]]
name = "frt"
path = "src/frt/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
toml = "0.5"
clap = { version = "4.0", features = ["derive"] }