on: [push]

name: build

jobs:
  build:
    name: Build frt
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y gcc-aarch64-linux-gnu gcc-mingw-w64-x86-64-posix

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Remove preinstalled Rust binaries
        run: |
          rm -rf ~/.rustup ~/.cargo

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.rustup
            ~/.cargo
          key: ${{ runner.os }}-frt

      - name: Rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s - --profile minimal --target x86_64-unknown-linux-gnu,aarch64-unknown-linux-gnu,x86_64-pc-windows-gnu -y

      - name: Build
        run: |
          ./scripts/ci/build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bin
          path: ./target/output/*

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: _rolling
          files: |
            ./target/output/*