on: [push]

name: build

jobs:
  build:
    name: Build frt
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y gcc-aarch64-linux-gnu gcc-mingw-w64-x86-64-posix

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s - --profile minimal --target x86_64-unknown-linux-gnu,aarch64-unknown-linux-gnu,x86_64-pc-windows-gnu -y

      - name: Build
        run: |
          ./scripts/ci/build.sh

      - name: Upload
        run: |
          set -x
          assets=()
          for asset in ./target/output/*; do
            assets+=("-a" "$asset")
          done
          hub release edit "${assets[@]}" -m "" _gh_assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}